### PR TITLE
Building Windows executable

### PR DESCRIPTION
**Pull request by forslund**
What it does
==========
* Makes mimic executable run on windows
* configure script run without warnings in MSYS/MINGW

Testing
======
Tested building on
* MSYS and MINGW (under Windows 7)
* Linux

### CODE REVIEW

**Comment by forslund** [comment]
I noticed that the -v path-to-flitevox can't use '\'

```bin/mimic.exe -voice voices\cmu_us_awb.flitevox -t "Hello there"```
will use default voice while 
```bin/mimic.exe -voice voices/cmu_us_awb.flitevox -t "Hello there"```

for me.

It seems like the check for if it's an url isn't the greatest:
```c
cst_voice *mimic_voice_select(const char *name)
{
[...]
    if (cst_urlp(name) ||       /* naive check if its a url */
        cst_strchr(name, '/'))
    {
        voice = mimic_voice_load(name);
        if (!voice)
            cst_errmsg("Error load voice: failed to load voice from %s\n",
                       name);
        mimic_add_voice(voice);
        return voice;
    }
[...]
```

**Comment by zeehio** [comment]
This `if` checks if it is a url (in `cst_urlp`) or if it is a file, doesn't it? Would you agree to add another `|| cst_strchr(name, '\\')` check, or replace the '/'  by a macro that either evaluates to '/'  or to '\' as required (Unix or Windows) and then merge this? Thanks again and sorry for reviewing everything late

**Comment by forslund** [comment]
You are correct. I think ```|| cst_strchr(name, '\\')``` is the better solution since you can use things like mingw to run mimic and then forward-slash is used. I'll look into it again in a serious way today or tomorrow during my lunch hour.

**Comment by zeehio** [comment]
Merged. Thanks!

**Pull request merged**
