### PR TITLE
Replace build system with autotools

### PR DESCRIPTION
**Pull request by zeehio**
This pull request replaces the build system in mimic with autotools.

## Advantages
- Standard build system (therefore more documented, easier to understand)
- `./configure` allows more fine tuning with standard `--enable-` arguments honoring passed compiler with `CC=` and options like `CFLAGS=` or `LDFLAGS=`.
- Reliable paralellization `make -j 8` or whatever the number of cores.
- Building static and shared libraries in both Windows and Linux
- Out of tree builds: `mkdir build; cd build; ../configure && make`
- Reliable transparent (no hacks) cross-compilation

## Disadvantages
- Mimic also requires automake and libtool to build it.

## Pending
- [x] Merge no_voice_list_branch
- [x] Change help message from --enable-cmu_us_kal to --disable-cmu_us_kal to reflect that it is enabled by default.
- [x] Fix autogen.sh so there is no hiccup (As mentioned below)
- [x] Ignore files mentioned below
- [x] Replace remaining case/esac with `AS_CASE`. See [AS_CASE](https://www.gnu.org/software/autoconf/manual/autoconf-2.62/html_node/Programming-in-M4sh.html) (and AS_IF too).
- [x] Replace `[[` with portable `test`.
- [x] Enable a travis test that will test cross-compilation continuously.
- [x] Try cross-compiling to ARM devices (raspberry pi)
- [x] Git rebase, merging and cleaning common commit messages

## Also takes care of
- Replace some small scripts that autogenerated simple C source files at build time with a C source file with simple macros (see `main/mimic_voice_list.c` and `main/mimic_lang_list.c`)
- Drop Windows CE support as it is old, was not tested in latest flite versions and we can't test it (and therefore properly support it)

### CODE REVIEW

**Comment by forslund** [comment]
As stated before, awesome work!

you might want to add the following to .gitignore

```
*.deps
*.dirstamp
```
and possibly
```
Makefile.
include/config.h
include/stamp-h1
```

I tested on windows under Msys2 and linux and all seems to work great. I got a small hickup on windows/msys2 where the configure script was rerun when I ran make for the first time but I can't seem to reproduce it.

`aclocal.m4` was modified by the build procedure the first time I ran it but nothing since. Might have been an user error =)

**Comment by forslund** [comment]
Yay, It passes! I've been watching you work all morning :)

**Comment by zeehio** [comment]
Sorry, I hope I did not spam you with lots of emails!

Later tonight I will clean all these commits. I will leave the windows+portaudio cross build in travis for future work. It is a pity because in my laptop works but I need to check all the dependencies and parameters.

**Comment by forslund** [comment]
No worries, it's been fun watching the progress. Great to have all the different builds on travis. 

I'll try to do some random testing, building pymimic with this and basic review tomorrow.

**Comment by zeehio** [comment]
@forslund Feel free to do a final review if you want, or a final test on your end.

Relevant changes:
- I skipped the tests that downloaded voices from URLs so the tests can run offline. Mocking a web server seemed a lot of work, but if you know of an easy and portable way to fake a web server locally we may use it.
- I dropped WinCE support. Flite documentation stated that it was untested on recent versions.
- Continuous integration working on OSX, Linux and crosscompiling on Windows.
- Readme documents how to cross compile, as it is the fastest way to get a functional `mimic.exe`.

**Comment by zeehio** [comment]
Oh, important! The standard autotools testing is `make check`, so there is we have changed from `make test` to `make check`.

**Comment by forslund** [comment]
@zeehio, I'll do my best reviewing it quickly. A small disclaimer, I'm no expert when it comes to autotools so I will probably miss details.

**Comment by zeehio** [comment]
@forslund Feel free to ask any questions. I will do my best to answer them although I am no expert neither :sweat_smile:

**Comment by forslund** [comment]
When configuring with ```../configure --enable-shared --prefix=`pwd`/install```

I get some errors when running `make install`

```
libtool: install: /usr/bin/install -c .libs/libmimic.lai /home/ake/tmp/mimic-orig/build3/install/lib/libmimic.la
libtool: install: warning: relinking `libmimic_lang_all_langs.la'
libtool: install: (cd /home/ake/tmp/mimic-orig/build3; /bin/bash /home/ake/tmp/mimic-orig/build3/libtool  --silent --tag CC --mode=relink gcc -g -O2 -no-undefined -o libmimic_lang_all_langs.la -rpath /home/ake/tmp/mimic-orig/build3/install/lib main/mimic_lang_list.lo libmimic.la libmimic_lang_usenglish.la libmimic_lang_cmu_grapheme_lang.la libmimic_lang_cmu_indic_lang.la libmimic_lang_cmulex.la libmimic_lang_cmu_indic_lex.la libmimic_lang_cmu_grapheme_lex.la -lm )
/usr/bin/ld: cannot find -lmimic_lang_usenglish
/usr/bin/ld: cannot find -lmimic_lang_cmu_grapheme_lang
/usr/bin/ld: cannot find -lmimic_lang_cmu_indic_lang
/usr/bin/ld: cannot find -lmimic_lang_cmulex
/usr/bin/ld: cannot find -lmimic_lang_cmu_indic_lex
/usr/bin/ld: cannot find -lmimic_lang_cmu_grapheme_lex
collect2: error: ld returned 1 exit status
libtool: install: error: relink `libmimic_lang_all_langs.la' with the above command before installing it
make[2]: *** [install-libLTLIBRARIES] Error 1
make[2]: Leaving directory `/home/ake/tmp/mimic-orig/build3'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/ake/tmp/mimic-orig/build3'
make: *** [install-recursive] Error 1
```

It creates the libmimic.so* files but no binary files in the install directory.

**Comment by zeehio** [comment]
I could reproduce the issue and this latest commit fixes it.

The fix was simply to change the order of the libraries so as if bar depends on foo, foo appears before bar. It seems that libtool or automake in Ubuntu does not respect library dependencies at make install relinking.

**Comment by forslund** [comment]
I can't test with *pymimic* because the hack I did to resolve library dependencies doesn't work in this setup. What is needed is to add library dependencies for libmimic.so but I think it's easier for me to test with *pymimic* so I think we can leave it as it is in this pull request.

**Comment by zeehio** [comment]
Is the pymimic code available somewhere (I can't find it or if I did then I have forgotten where I put it) or are you still working on it?

Before merging this, I will fix the install path of the library headers and create a pkg-config pc file to make it easier and portable to link against mimic

**Comment by forslund** [comment]
I have a repo at https://github.com/forslund/pymimic

It's still very basic but it can produce sound from text. It is still very much a work in progress, right now I'm working on the utterance parts to be able to manipulate and get more information.

I basically build my own libpymimic.so using the intermediate `.shared.a` files mimic generated.

**Comment by forslund** [comment]
Ok, it was I who was stupid. This setup will work just fine, my hack is not even necessary.

I'll do some more testing but I think this is mergable. I'll await the pkg-config pc-file and do a final check and if nothing weird pops up I'll go ahead and merge this.

**Comment by zeehio** [comment]
Now headers are installed in a more organized way (prefix/include/mimic/).
Also, there is a pkg-config file installed.

As always, build with:
```
./configure --prefix="/tmp/mytest" --enable-shared
make
make install
```
Now, if you have another software you want to link against mimic you can use:

```
export PKG_CONFIG_PATH=/tmp/mytest/lib/pkgconfig/

gcc `pkg-config --cflags mimic` -o mysoftware mysoftware.c `pkg-config --libs mimic`
```

**Comment by forslund** [comment]
This looks excellent, merging. Thanks for this huge overhaul!

**Pull request merged**
