### PR TITLE
Continuous integration support in mimic

### PR DESCRIPTION
**Pull request by zeehio**
This pull request is related to issue #26. Please do not merge until it's done.

- [x] Added gcov support to configure script
- [x] Added Travis support
- [x] Code coverage analysis with codecov.io
- [ ] Static code analysis (with coverity)

### CODE REVIEW

**Comment by zeehio** [comment]
@ryanleesipes If the coverity terms and conditions are fine to you, please accept the request I have sent you

**Comment by zeehio** [comment]
coverity suggests to set up travis first, so this is ready to be merged.

One limitation of this PR is that I have switched to using full paths instead of relative paths. This makes build commands a bit longer, but I did not know how to avoid it without changing the build process significantly more.

@forslund @LongBoolean would you mind reviewing it? I don't like to merge my own pull requests.

**Comment by LongBoolean** [comment]
I have a few questions: What is the desired goal going forward with coverty and travis? How will these tools be used, and are all contributors required to use them?(are they optional if they don't fit your style?) Is the goal to create unit tests for existing cases where there is a clear input and output, or is the goal to go full modern TDD and only write tests first before implementation?

**Comment by ryanleesipes** [comment]
@zeehio done. Do you need anything from me for the TravisCI? I know I said I would do it, but I'm not exactly sure and it is marked at done. But I realize since it is a public repo it should be good to go. Just let me know what you need from me.

**Comment by zeehio** [comment]
@ryanleesipes everything looks good now I think, thanks!

@LongBoolean, good points. The goal of Travis, codecov and Coverity is to monitor the source code to check for potential regressions (running tests) and discover issues (forgot to free a variable...). No developer is forced to do anything or follow any development methodology, these tools can be ignored. However they will help us (at least me) spot issues faster.

Regarding Test Driven Development, if you like it you can follow it, if if you don't then don't. Personally I am not a fan of "all or nothing" methodologies, for some issues writing a test beforehand can be beneficial and practical but I don't think all issues require that (although a test in most cases is welcome to prevent the issue from repeating in the future).

In general I believe that having good tests is beneficial to prevent regressions, and I would rather see the code coverage  metric increase. In the existing unit tests we cover 15% of the code base, adding a `mimic -t "hello" ` increased the coverage to 30%.

I hope to have answered your questions :-)

**Comment by forslund** [comment]
Tested locally and reviewed. Everything looks good as far as I can see.

**Comment by LongBoolean** [comment]
@zeehio Ok thank you for explaining your reasoning.

**Pull request merged**
