### PR TITLE
Build mimic with -Wall -Wextra -Werror

### PR DESCRIPTION
**Pull request by zeehio**
This pull requests allows us to build mimic with GCC with -Wall -Wextra without any warning.

- No function arguments are changed, so unused arguments are "used" with `(void) argument`.
- Some structures had uninitialized fields, that are now set to 0 or NULL, as this is the equivalent of the calloc calls used in mimc's cst_alloc.
- Some `const` was lost in the voices. The C standard did not allow for a const there, so I believe we were triggering undefined behaviour. I believe it is better to follow the rules and drop consts were could not be there. If someone requires them, then someone will have to work on proper (as in well defined) support.
- Some POSIX options were updated. In particular:
    * `src/audio/au_alsa.c` uses `usleep`. It is removed from POSIX2008, so we should use `nanosleep` instead. The source has the `_BSD_SOURCE` definition by alsa requirement.
    * `src/utils/cst_mmap_posix.c` was updated to better conform to POSIX. Some Blackberry specific remnants were kept under `ifdef __QNXNTO__` and have been dropped.
- A pointer to `int` cast has been fixed by using `intptr_t`.
- Some signed vs unsigned issues have been dealt with.

### CODE REVIEW

**Comment by forslund** [comment]
Nice! I'll review as soon as I can!

**Comment by forslund** [comment]
Did a quick test, and the voice order is changed. was this intentional? Now the default voice is 'slt'.

**Comment by forslund** [comment]
Should these flags be added to the CFLAGS maybe? At least -Wall?

Personally I'm not certain -Wextra is desirable? It warns about uninitialized fields in structs and I'm a heavy user of the C auto-initialization. I guess my muscle memory has to be purged =)

**Comment by zeehio** [comment]
I was not aware of the default voice change. This is surprising. If you can't look into it I can do it, just say so ;-)

I will push a commit to add `-Wall -Werror` to the default `CPPFLAGS`. As you say `-Wextra` may be too picky.

Eventually I would like to go for the `--std=c99` flag so we decide when we change from standard version rather than letting each compiler default option choose the C standard for us. I would like to be aware of the standards and features we are using in mimic and try to stick to a few of them that are not obsolete. BSD, POSIX and GNU standards can be enabled per source file if required (in OS dependent audio modules for instance) through the [feature test macros](http://man7.org/linux/man-pages/man7/feature_test_macros.7.html).

Indeed the C99 standard compliance may not be a priority, but compiling under `-Wall --Werror` is a priority if we expect authors bringing support to other languages to comply with warning free code.

**Comment by forslund** [comment]
You might have a point to not move to `std=c99`before we know exactly what set of standards we are using.

In the meantime I have no objections to merging this, so merging.

Btw, thanks for pointing out the feature_test_macros, they look quite useful

**Pull request merged**
