### PR TITLE
README.md:insert space after 'if' (example code)

### PR DESCRIPTION
**Pull request by andy5995**
* Whether you have signed a CLA (Contributor Licensing Agreement)

No I have not.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Andy,

Thanks for helping to improve Mycroft!

I know it may seem like a small contribution however to protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any contributions to a Mycroft repository. This agreement makes it crystal clear that along with your changes you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

It might seem overkill on small PR's like this one, however it greatly simplifies our processes to have a blanket rule for all contributions. I hope you understand.

On the plus side - you will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

**Comment by andy5995** [comment]
Ah, thanks for the explanation. I don't completely understand the need for it (I haven't heard of any situations where GitHub users or project maintainers have had issues when policies like that aren't in place), but of course you are free to have that policy. Good luck with your project! :)

**Comment by andy5995** [comment]
By the way, I started filling out the license form when I submitted the PR, but when trying to enter my name, only one character could be entered into the field.

* Firefox 99.0.1 (64-bit)
* Manjaro 21.2.6

**Comment by krisgesling** [comment]
Thanks for the heads up, I'll look into it.

I know it's going to turn some people off however it came about because we ran into headaches early on. A more recent example is the [websocket-client project](https://github.com/websocket-client). They had to go through an extremely long process of personally contacting every single contributor because of a license mismatch issue. For those they couldn't reach they had to remove all code and re-implement their contributions. 

It's still the right thing to do to contact everyone, the difference is months of painful work vs doing a reasonable best effort and then moving forward with the blessing of those who are still engaged.

**Comment by andy5995** [comment]
@krisgesling I'll keep all that in mind. I might want to look at this project more in-depth when I have less on my plate. Cheers!

**Pull request closed without merging**
