### PR TITLE
Initial ICU support for multilingual text analysis

### PR DESCRIPTION
**Pull request by zeehio**
The [International Components for Unicode](https://en.wikipedia.org/wiki/International_Components_for_Unicode) libraries provide Unicode support into mimic. They can handle Unicode regular expressions and conversions to lower case and upper case, among many other things. We need these tools for proper token_to_words analysis in languages different than English.

This pull request just brings in some basic functions for regular expression matching and upper/lower case conversion. I don't see the benefit of providing a wrapper for each ICU function, although providing a wrapper for some generic functions is --from my point of view-- beneficial (for instance as an example of "how to use ICU").

This PR does not replace any mimic function so for now we will have two regular expression engines (the one embedded in mimic and the one from ICU) and two sets of case conversion functions. I have not compared the performance of both engines, although I can imagine that the ICU will be slower as it considers many more cases.

Depending on the size of the ICU libraries and their performance we may decide to drop the embedded regular expression engine. For now, I would rather go for "let's make things work" and later we will decide on how and if we optimize them.

Feel free to review and comment it.

### CODE REVIEW

**Comment by zeehio** [comment]
Feel free to review and merge whenever you can @forslund. No hurries :-)

**Comment by forslund** [comment]
I've started to read through it. The only thing I've noticed you just fixed =) My plan is to do a more in depth review during the weekend.

**Comment by forslund** [comment]
Everything looks good. I created a couple of extra tests while reviewing (see #72) that may be of interest to include.

The minor complaint I could have is that there is lots of code duplication in the `cst_tolower_l()` and `cst_toupper_l()`. I prepared a possible way to get around that see #73 (it also fixes a warning about `cst_errmsg()`)

**Comment by forslund** [comment]
Merged!

**Pull request merged**
