### PR TITLE
Fix voice ap for Raspberry Pi

### PR DESCRIPTION
**Pull request by forslund**
This is a workaround for the *ap* voice failure on Raspberry Pi (#99) . I'm not 100% sure what's going on and if someone has a more correct way to fix the issue I'd be happy.

I've verified that this works on my raspberry Pi and checked that the voice is still working on my desktop, but I'd like to have it running on a couple more Rasberry Pi's before merging.

The PR is quite messy but shows my work, it should be squashed before merging.

### CODE REVIEW

**Comment by zeehio** [comment]
The global diff of this PR is very small, but I fail to see what is going on. Do you think there a bug in the compiler?

**Comment by forslund** [comment]
@zeehio I can't really make sense of it either. I reverted the file and re-applied your old code line by line until it broke when I readded
```c
float vid_gb_ap_dynwin[] = { -0.5, 0.0, 0.5 };
```
So what I did was just a quick workaround to remove the warning while still keeping the `const` declaration.

The way you did it is more correct and *should* work, so I think it might be a gcc-bug. I can see if I can install gcc 6.x on my Pi and retry master.

**Comment by forslund** [comment]
Tested gcc-6 on the raspberry pi. The issue remains on master...

**Comment by zeehio** [comment]
Unfortunately I don't have a raspberry pi available for testing right now. I wish I had my Mycroft unit :sweat_smile:

The only other test I would suggest to try (but we can merge if you don't want to spend more time on this) would be to try using the `f` suffix in the floating point numbers, just in case the bug is triggered because of not specifying the `f`:

```c
const float vid_gb_ap_dynwin[] = { -0.5f, 0.0f, 0.5f };
```

Feel free to ignore this suggestion and merge the PR if you are tired of waiting for things to compile. The solution is there and it works, now it is more of a curiosity of mine...

**Comment by forslund** [comment]
I'll give that a try tonight and see if it works.

Den 10 mar 2017 12:50 em skrev "Sergio Oller" <notifications@github.com>:

**Comment by forslund** [comment]
I tested it but it did not do any difference.

I noticed that the voice is not entirely missing, it's just very low and has very bad quality. But I can make out that it's actually saying what I just typed in. The real issue could just as well be in the code that uses the dynwin-table.

**Comment by zeehio** [comment]
Smart move! I hope this works :+1:

**Comment by forslund** [comment]
It seems to work, tested on my raspberry and my laptop without issues.

Den 12 mar 2017 23:08 skrev "Sergio Oller" <notifications@github.com>:

**Comment by aatchison** [comment]
How are we doing here?

**Comment by zeehio** [comment]
We don't fully understand where the error is, but it seems @forslund has solved it.

I don't know if @forslund wants anyone else to try this branch. It looks ready to be merged to me.

**Comment by aatchison** [comment]
Nice. Ok, I'll check it out.

**Comment by forslund** [comment]
I tested the latest update in a hurry on Sunday and it works as far as I can see. I'd be happy to hear a second opinion.

See my build instructions [here](https://github.com/MycroftAI/mimic/issues/99#issuecomment-285858550)

**Pull request merged**
