### PR TITLE
Spanish language analysis and voice

### PR DESCRIPTION
**Pull request by zeehio**
This PR provides initial Spanish support to mimic (related to issue #3).

There is still work to do, but this is mergeable and barely usable.

The good things are:
- It works. mimic speaks Spanish and it is understandable.
- I don't get any memory leaks with valgrind (in my tests).
- Further improvements will be easily noticeable, so other developers with knowledge of Spanish may want to contribute more, and I won't be the bottleneck anymore.
- Other languages can start to see how language support can be done.

These are the things that need to work:
- Improve text analysis (numbers are not spoken, except the 17 given as an example). In general  symbols are not pronounced (only the € character is, as an example).
- Pauses related to punctuation signs are not yet respected. (only two newlines make a pause).
- Adding transcriptions manually for words badly pronounced is not yet straightforward
- The phonetic transcription is done word by word, like in English. If we were to transcribe the whole sentence at once some phonetic transcription errors might disappear.
- Adding transcriptions manually for words badly pronounced is not yet straightforward
- The Part of speech guesser needs someone to finish adding all the Spanish pronouns and conjunctions. This is currently used for the intonation model, so the intonation may improve a bit with this done.

While the PR is quite big it is quite well commented (at least with good introductions). I hope it can be easily reviewed, feel free to ask any question.

### CODE REVIEW

**Comment by jorgegarciadev** [comment]
Hi, I've tried it, but I have a problem. When choosing the voice, with the `--voice`, flag I get: `voices/cstr_upc_upm_spanish_hts.hts voice does not have expected header`. What I'm missing?

**Comment by forslund** [comment]
I seem to have the same issue. running `file cstr_upc_upm_spanish_hts.htsvoice` results in

`cstr_upc_upm_spanish_hts.htsvoice: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz`

**Comment by zeehio** [comment]
Could you try to `./mimic -lv` to see if the voice is compiled?

And then use it with:
`./mimic -voice cstr_upc_upm_spanish_hts -t "hola amigo"`

Using the filename directly does not work for hts voices as they need both the code part (compiled in mimic) and the data part (in a file). The same happens with the `slt_hts` voice.

**Comment by jorgegarciadev** [comment]
I tried, and the voice doesn't show up

**Comment by forslund** [comment]
For me it shows up but it seem to fall back to default slt voice

**Comment by forslund** [comment]
You can disregard the `file` output from me, I must have messed up a command line and written to the hst file. Checking it out restores it to correct format. 

Now it works but is really slow for the phrase "Hola" and very fast for "Hola, que tal"

**Comment by zeehio** [comment]
(I will recheck once I'm in front of the computer)

**Comment by jorgegarciadev** [comment]
I tested again on Ubuntu 16.04, and now the voice shows up and it works. Now I'm having the same issue than @forslund, when the text is just a word It's very slow.

**Comment by zeehio** [comment]
I broke something on Saturday, I will need some time to fix it. :-( Sorry for wasting your time

**Comment by forslund** [comment]
That's what reviews are for. No time wasted, the work you've put in is awesome!

**Comment by jorgegarciadev** [comment]
No problem

**Comment by zeehio** [comment]
I forgot to clear the Saga output between transcriptions and this was sometimes adding additional wrong phonemes. This is fixed.

With respect to the long duration of the phonemes with short sentences and the fast speed, there is not much I can do, as I don't have the original recordings. The only HTS Spanish voice I found was this one http://homepages.inf.ed.ac.uk/jyamagis/software/page54/page54.html and it has the same problem (I tested with Festival). I must say that voice is from 2008 and it is now unsupported.

To fix this speed issue I would need to edit the speech model (the voices/*.htsvoice file). In order to do that I would need to interpret the model file and edit it. While it is possible, I don't have a tool to do it and I would need a lot of work to hack it.

Other speech models (the Spanish diphone voices I found https://packages.debian.org/buster/festvox-ellpc11k ) are non-free as they are for non-commercial purposes only.

The good part is that in this PR there is a Spanish language model, so with some recordings it should be possible to train a voice.

**Comment by forslund** [comment]
Thanks Zeehio, for longer sentences it works fine. I can modify the duration_stretch parameter to get the shorter messages sounding OK.

Will continue to review during the coming days.

**Comment by zeehio** [comment]
Note that some parts of this PR are from my own work and other parts are from third parties, namely the Universitat Politecnica de Catalunya, t'he University of Edinburgh, and the Universidad Politécnica de Madrid. It changes some parts of mimic to gplv3 because of the saga license so it may not be good for merging. 

I hope this comment is enough to make this pull request CLA compliant

> Should You wish to submit work that is not Your original creation, You may submit it to the 
Project Manager separately from any Contribution, identifying the complete details of its 
source and of any license or other restriction (including, but not limited to, related patents, 
trademarks, and license agreements) of which you are personally aware, and conspicuously 
marking the work as "Submitted on behalf of a third-party: [named here]".

**Comment by zeehio** [comment]
We are going to split mimic into several components anyway, so I would rather not merge this right now to keep licenses simple.

**Comment by penrods** [comment]
I agree, until we restructure things we shouldn't incorporate the pieces licensed under GPLv3.  Once we can place those pieces in their own repos we can have a clear line between these differently-licensed components.

**Comment by zeehio** [comment]
@penrods I already restructured the mimic repository into several modules. Each of the modules (except for the core) builds a mimic plugin. A mimic plugin is a shared library loaded at runtime (with dlopen in POSIX systems, with its equivalent on Windows) by mimic.

- https://github.com/zeehio/mimic-core
- https://github.com/zeehio/mimic-english
- https://github.com/zeehio/mimic-spanish
- https://github.com/zeehio/mimic-vid_gb_ap
- https://github.com/zeehio/mimic-cmu_us_slt
- ... (There are more than 10 mimic-* repositories)

It is working. In order to test that everything is integrated properly, I created: https://github.com/zeehio/mimic-full that uses git submodules to pull all the dependencies, optionally filtering out the GPL ones.

@forslund is going to test it on the pi one of these days. With the new structure the licensing issues will be easier

**Comment by forslund** [comment]
@zeehio I was going to contact you about migrating the repos over to the mycroftai github account in the morning but wanted to wait until I knew you were back from the playa

**Comment by zeehio** [comment]
Cool, I will start transferring them in the next 24 hours :+1:

**Comment by zeehio** [comment]
I can't transfer the repositories to the MycroftAI organization because I don't have permission to create repositories there 😌 There are three options:

a) I get the permission temporarily so I can transfer the repositories
b) @forslund creates the repositories and pushes the contents of the repositories I created there
c) We create an intermediate organization, I transfer the repositories there, and from there someone with permissions transfers them to MycroftAI

I am happy with any of the options.

**Comment by forslund** [comment]
@spenrod wanted the repos in mycroftai. I'll create the repos tomorrow morning and push over your repos. We should give you permissions to do this (and create new ones as needed) in the long run.

**Comment by zeehio** [comment]
Wonderful

**Comment by penrods** [comment]
@zeehio I'm happy to give you additional permissions, you are certainly a trusted contributor.  I have done this, so you can work with @forslund in whatever way is most convenient.

**Comment by zeehio** [comment]
@penrods you gave me admin permissions to this mimic repository, but not permissions to create new repositories under MycroftAI. I believe that to do that I would need to have admin privileges in the whole MycroftAI organization, and right now I don't want that responsibility. To push this repo transfer as forward as I can I created a dummy organization named TransferMimic and I sent two invitations to both @penrods and @forslund so both of you become owners of all the mimic-* repositories as well, and you can transfer all the repositories to the MycroftAI organization easily. I will delete the dummy organization once the repo transfer is done. It all depends on both of you now ;-)

**Pull request closed without merging**
