### PR TITLE
Fix musl compatibility

### PR DESCRIPTION
**Pull request by PureTryOut**
This MR fixes compilation on musl (rather than glibc) systems such as Alpine Linux.

To test, try to compile this project on musl before and after using this PR.
Test on glibc if it compiles fine like before.

I have signed the CLA.

### CODE REVIEW

**Comment by PureTryOut** [comment]
The CI failure seems unrelated, it's missing a library on macOS?

**Comment by forslund** [comment]
Yeah, the iOS test can be ignored. Has been fixed a couple of times but keeps breaking

**Comment by forslund** [comment]
This looks good, Going to spin up a vm and try it out but should be no issues

**Comment by forslund** [comment]
Tested both on Ubuntu and on alpine. Works on both. Merging this, will tag a new release tomorrow morning.

**Pull request merged**
