### PR TITLE
Fix build: HTSEngine: use HTS_free

### LINKED ISSUE #231: Error when running 'make'
**Describe the bug**
Error when running 'make'. 
```
Making all in .
make[1]: Entering directory '/home/ddmin/Downloads/mimic1-1.3.0.1'
  CC       main/mimic_main.o
  CC       main/mimic_lang_list.lo
  CC       src/audio/libttsmimic_la-au_alsa.lo
  CC       src/audio/libttsmimic_la-auclient.lo
  CC       src/audio/libttsmimic_la-au_command.lo
  CC       src/audio/libttsmimic_la-audio.lo
  CC       src/audio/libttsmimic_la-au_none.lo
  CC       src/audio/libttsmimic_la-au_oss.lo
  CC       src/audio/libttsmimic_la-au_portaudio.lo
  CC       src/audio/libttsmimic_la-au_pulseaudio.lo
  CC       src/audio/libttsmimic_la-auserver.lo
  CC       src/audio/libttsmimic_la-au_streaming.lo
  CC       src/audio/libttsmimic_la-au_sun.lo
  CC       src/audio/libttsmimic_la-au_wince.lo
  CC       src/cg/libttsmimic_la-cst_cg.lo
  CC       src/cg/libttsmimic_la-cst_mlsa.lo
  CC       src/cg/libttsmimic_la-cst_mlpg.lo
  CC       src/cg/libttsmimic_la-cst_vc.lo
  CC       src/cg/libttsmimic_la-cst_cg_load_voice.lo
  CC       src/cg/libttsmimic_la-cst_cg_dump_voice.lo
  CC       src/cg/libttsmimic_la-cst_cg_map.lo
  CC       src/cg/libttsmimic_la-cst_spamf0.lo
  CC       src/hrg/libttsmimic_la-cst_utterance.lo
  CC       src/hrg/libttsmimic_la-cst_relation.lo
  CC       src/hrg/libttsmimic_la-cst_item.lo
  CC       src/hrg/libttsmimic_la-cst_ffeature.lo
  CC       src/hrg/libttsmimic_la-cst_rel_io.lo
  CC       src/hts/libttsmimic_la-flite_hts_engine.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_audio.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_engine.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_misc.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_pstream.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_sstream.lo
  CC       src/hts/hts_engine_API/lib/libttsmimic_la-HTS_model.lo
In function 'HTS_Model_load_pdf',
    inlined from 'HTS_Model_load' at src/hts/hts_engine_API/lib/HTS_model.c:745:8:
src/hts/hts_engine_API/lib/HTS_model.c:701:7: error: 'free' called on pointer '*model.npdf' with nonzero offset 16 [-Werror=free-nonheap-object]
  701 |       free(model->npdf);
      |       ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:3743: src/hts/hts_engine_API/lib/libttsmimic_la-HTS_model.lo] Error 1
make[1]: Leaving directory '/home/ddmin/Downloads/mimic1-1.3.0.1'
make: *** [Makefile:4809: all-recursive] Error 1
```

**To Reproduce**

```
1. $ sudo pacman -S --needed install gcc make pkg-config automake libtool alsa-lib
2. Download v1.3.0.1 release source code
3. $ cd mimic1
4. $ ./dependencies.sh --prefix="/usr/local"
5. $ ./autogen.sh
6. $ ./configure --prefix="/usr/local"
7. $ make
```

**Environment**
Linux 5.15.74-3-MANJARO

### PR DESCRIPTION
**Pull request by DimStar77**
* Fix build, fixes #231

* Whether you have signed a CLA (Contributor Licensing Agreement)
That sounds not CLA-worthy contribution (not signed)

### CODE REVIEW

**Comment by forslund** [comment]
The fix sounds sound. Many thanks! Will run some basic tests when I get home. @krisgesling would it be ok to merge without CLA?

**Comment by krisgesling** [comment]
Thanks for this!

I know it may seem like a small contribution however to protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any contributions to a Mycroft repository. This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.

It might seem overkill on small PR's like this one, however it greatly simplifies our processes to have a blanket rule for all contributions. I hope you understand.

On the plus side - you will also be added to [our list of excellent human beings](https://github.com/MycroftAI/contributors)!

Please visit https://mycroft.ai/cla to initiate this one-time signing.

Thank you!

**Comment by DimStar77** [comment]
Done - as individual contributor

**Comment by krisgesling** [comment]
Thanks for understanding - CLA received and you've been added to our list of contributors :tada: 

I'll wait for @forslund to confirm before we merge this in.

**Comment by forslund** [comment]
Verified and working excellently. Merging

**Pull request merged**
