### PR TITLE
Replace icu with pcre

### LINKED ISSUE #119: [Build error] Libicu 58 not found
Hi! I was trying to install mycroft-core on my ubuntu 17.04 desktop (64-bit), and an error prompted saying:

```
/usr/bin/ld: warning: libicui18n.so.58, needed by ./.libs/libttsmimic.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.58, needed by ./.libs/libttsmimic.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.58, needed by ./.libs/libttsmimic.so, not found (try using -rpath or -rpath-link)
```

I couldn't find the mentioned package on the package manager.
Is there anything I can do to make this work!
Thx!

### PR DESCRIPTION
**Pull request by zeehio**
Closes #119  and #120.

I added a `dependencies.sh` script that builds third party dependencies if they are not installed.

With this PR icu is replaced by pcre2.

Feel free to review whenever you have the time. Notice that the pcre2 third party library is left "as it is"

### CODE REVIEW

**Comment by zeehio** [comment]
Note to self: I need to add thirdparty/pcre2/ to the COPYING file.

**Comment by forslund** [comment]
I've started to review this now, sorry for the delay. The first thing I notices is that the `dependencies.sh` needs to be run as root since it performs a `make install`. I suggest to try a `sudo make install` and in case that the user is in sudoers she/he will be prompted to enter password and can proceed. If that fails (user is not in sudoers) Print a text to log in as root and run make install in the correct directory.

Second, could we use git submodule to leave the pcre tree outside mimic allowing the dependencies script to pull it down if install is needed?

**Comment by zeehio** [comment]
With respect to the `make install` being run as `sudo`... I will change it to detect if we have write access to the prefix and run either `make install` or `sudo make install` as needed.

For instance, running `./dependencies.sh --prefix="$HOME/mimic"` should be fine without root permissions.

**Comment by forslund** [comment]
Sounds great!

Den 19 juni 2017 11:38 fm skrev "Sergio Oller" <notifications@github.com>:

**Comment by forslund** [comment]
The implementation looks great, seems nice and simple. And I couldn't see any obvious mistakes.

Merge when you feel ready!

**Comment by zeehio** [comment]
Thanks, these are the changes I've done:

- If pcre2 is not available, then it is downloaded, md5 verified, unzipped, patched (because of a bug already fixed upstream), built and installed. pcre2 sources are not bundled, but I'm not using git submodules (because pcre2 uses svn and not git, so there is not a great advantage)

- dependencies.sh tries to `make install`. If it fails it gives a message and tries to `sudo make install`. If it fails again it give a message and exits.

If travis is happy then I will merge this and I will move on to rebase the other PR.

**Pull request merged**
