### PR TITLE
Add gcc-6 support (Closes #95)

### LINKED ISSUE #95: Build fails with gcc 6.2.0 on ubuntu 16.10
```
 make
Making all in .
make[1]: Entering directory '/mimic'
  CC       src/audio/libttsmimic_la-au_alsa.lo
In file included from /usr/include/stdlib.h:24:0,
                 from src/audio/au_alsa.c:48:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
cc1: all warnings being treated as errors
Makefile:2985: recipe for target 'src/audio/libttsmimic_la-au_alsa.lo' failed
make[1]: *** [src/audio/libttsmimic_la-au_alsa.lo] Error 1
make[1]: Leaving directory 'mimic'
Makefile:4111: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

### PR DESCRIPTION
**Pull request by zeehio**
Let's wait to see if travis is happy...

### CODE REVIEW

**Comment by forslund** [comment]
Should the old define be removed? As I've read the docs (and tested) the `_BSD_SOURCE` is ok if  `_DEFAULT_SOURCE` is present. Having them both no backwards compatibility is lost.

**Comment by forslund** [comment]
Also (and not very important at this stage since the fix resolves the issue at hand), just installing gcc-6 did not update `glibc` >= 2.20 and I could not see the problem without editing `/usr/include/features.h` to warn about the usage of `_BSD_SOURCE`.

Is there a way to in the future add a separate glibc version for the gcc-6 test?

**Comment by forslund** [comment]
Reading some more it seems the `_DEFAULT_SOURCE` and `_BSD_SOURCE` is only useful if `-ansi` is added to CFLAGS so readding is unnecessary unless we intend to clean up the project enough to use `-ansi` with bare minimum of posix.

This looks good and tests with modern gcc is excellent to have. Thank you @zeehio, great work as usual!

**Comment by zeehio** [comment]
I believe having both defines is the best choice for compatibility. I'll fix this soon.

We are currently enforcing C99 compliance with `--std=c99`, we need the `#define` due to ALSA, that requires some noncompliant feature http://stackoverflow.com/questions/32672333/including-alsa-asoundlib-h-and-sys-time-h-results-in-multiple-definition-co

**Comment by forslund** [comment]
Hmm, I'll have to see how to best merge this both into master and development.

**Comment by forslund** [comment]
@zeehio I could compile your branch on debian old-stable (sqeeze) which doesn't respect `_DEFAULT_SOURCE`. If I add `-ansi` it fails on the alsa code as expected.

**Comment by forslund** [comment]
Looks good, I'll check it against my antique debian installation at work tomorrow morning and if there are no problems I'll go ahead and merge.

**Comment by zeehio** [comment]
I have now used more specific well defined feature test macros:

C99 + POSIX.1-2001 + alloca compliance
    
This commit:
- Adds the use of `--std=c99` in travis so we stick to a specific C standard.
- Uses a more specific `_POSIX_C_SOURCE` (200112L) feature test macro (instead of `_DEFAULT_SOURCE` or `_BSD_SOURCE`)
- Includes `alloca.h` (required by ALSA, as done in [other projects](https://lists.mplayerhq.hu/pipermail/mplayer-dev-eng/2008-July/058081.html))
- Should provide compatibility with glibc 2.3.3 or later (Released in 2003)

Let's hope for the best :smile:

**Comment by forslund** [comment]
@zeehio, I tested some during lunch and I think it might be best to have the `_POSIX_C_SOURCE 200112L` define in all unittest files since the unittest can include the same headers that CUtest includes (before cutest.h is included).

The other option is to make sure `cutest.h` is the first include in the unittests.

Or option 3 add `-D_POSIX_C_SOURCE=200112L` to the c-flags for the unittests

**Comment by zeehio** [comment]
Or option 4, submit a patch to `cutest.h` so cutest does not use nor enable any POSIX feature, if the user has requested strict C standard compliance.

https://github.com/mity/cutest/pull/7

**Comment by zeehio** [comment]
The build succeeded on travis, so I squashed all the commits (no need of them). Looks good to me to merge, but maybe @aatchison and @forslund want to try it first on their machines...

@forslund, to merge I suggest you to merge into master, tag 1.2.1, and then merge master into development. But feel free to do as you prefer

**Comment by aatchison** [comment]
Sorry, I forgot to test. Just a min

**Comment by aatchison** [comment]
This branched worked for me on 16.10 ;)

**Comment by forslund** [comment]
Looks excellent. Awesome work!

**Pull request merged**
