### PR TITLE
Use bellbird's hand optimized mlsa filter

### PR DESCRIPTION
**Pull request by forslund**
Replace the mlsa filter originally from flite with the hand optimized
ones in bell bird.

# Preliminary benchmark

Using the `docs/alice` text.

## With Bellbird optimizations

real    1m44,649s
user    1m43,712s
sys     0m0,696s

## Without:

real    3m47,627s
user    3m46,860s
sys     0m0,732s

### CODE REVIEW

**Comment by zeehio** [comment]
I am sure you checked and Peter did as well in Bellbird but just to be sure... Are the generated audio files equal?

Quite impressive to see how good human optimized code is with respect to letting the compiler do the optimizations!

**Comment by forslund** [comment]
I didn't expect them to be, but according to diff they're identical. Please try it out if you have time after you get back from the _playa_

**Comment by zeehio** [comment]
Could you please add the support as well to hts voices? 
https://github.com/peterdrysdale/bellbird/blob/master/src/hts/HTS_vocoder.c

Looks mergeable to me :-)

**Comment by penrods** [comment]
Wow, those are some impressive optimizations!

**Comment by forslund** [comment]
@zeehio I can definitely give it a shot!

**Comment by penrods** [comment]
Just curious -- is this on hold?  I glanced at the CI log and it appears the win-shared build just stalled, not a definitive failure.

**Comment by zeehio** [comment]
The PR is fine, I believe @forslund was going to add the optimization as well to the HTS voices, so both voice techniques benefit from this optimization. This looks good to be merged to me, I leave it up to him to decide if he wants to merge now or wait for later 👍 . In any case, we are splitting the mimic repo in several smaller repositories, both for practical reasons (smaller repository size, faster compilation times) and for licensing reasons (the Spanish language support is GPL due to the Saga library dependency). Due to this split, this change will have to go to the https://github.com/MycroftAI/mimic-core repository and the HTS patch will need to go to the https://github.com/MycroftAI/htsengine_meson

**Comment by penrods** [comment]
No stress, I know a total revamp is near (for good reason!) and suspected that might be the reason to just hold off on this.

**Comment by forslund** [comment]
The hts was more different than the clustergen than I originally thought so I didn't quite finish and then I got sidetracked. Will fix it today/tomorrow and then move the changes over to the new system.

**Comment by forslund** [comment]
Finally! Been battling for a day with a memory issue and have finally found it. Cleanup and then maybe HTS will be ready... unless I mess things up even more.

**Comment by zeehio** [comment]
I'm checking the PR from my phone and it looks great and clean! Just a couple of comments:

The Bellbird optimization only works for a pade order of 5. For that reason the `SPEED_HACK` #define in clustergen voices is correctly removed in this pull request. HTS voices have the equivalent `HTS_EMBEDDED` #define at https://github.com/forslund/mimic/blob/4a9ad5ae169e3936c2f3d165c155ac77187f7d60/src/hts/hts_engine_API/lib/HTS_hidden.h#L447 . Maybe this `HTS_EMBEDDED` define should be removed as well, as the Bellbird optimization does not work if the pade order is not 5. I don't recall the effect of `GAUSS` and `IRLENG` so I don't know if they are related to the Pade order in any way. Feel free to either check if they are compatible with the Bellbird optimization or more simply drop the whole HTS_EMBEDDED block.

The second comment is not code-related: could you please add the new file to the COPYING file? And maybe add Peter Drysdale and the Bellbird project to the ACKNOWLEDGEMENTS file as well?

Thanks for all this work!

**Comment by forslund** [comment]
Of course, will fix this.

Should have thought of adding him to acknowledgements, the result of the optimizations are amazing

**Comment by forslund** [comment]
As far as I can determine both GAUSS and IRLEN does some optimization and still works so I've kept those.

I didn't find any copyright period of bellbird, not sure if that's an issue in the COPYING file.

**Comment by zeehio** [comment]
The year in the copyright is used to determine when the copyright will expire. A work that has not done any copyrightable change in 200 years (well, much less than 200, but it depends on the legislation) is public domain.
 
The safest thing for you to do when you receive a work without copyright year is to assume the last change was done the day you received the work. Therefore here you could use 2017 safely.

Let's merge this now. It is good!

**Comment by forslund** [comment]
Will add it to the new repos during the week

**Pull request merged**
