### PR TITLE
Sleep before drain to fix issue #18.

### LINKED ISSUE #18: Mimic doesn't read whole text
In command line I tried running ./mimic -t where string was about 1800 characters long, but Mimic didn't read the whole thing. It got to about one third of the text and then just stopped mid-word at about 460 character.
All characters were either letters, numbers or punctuation, combined into proper grammatical sentences.
I tried with other long texts and got same result.

I use updated Fedora 23 x86_64 and BASH as command line interpreter.

### PR DESCRIPTION
**Pull request by zeehio**
@forslund would you mind testing this?

It works on my computer and it seems that it's the solution used in other projects:

http://mailman.alsa-project.org/pipermail/alsa-devel/2012-November/057129.html

If it works for you, closes  #18

### CODE REVIEW

**Comment by forslund** [comment]
Looking at this at the train on my phone. Am I correct to assume that the delay is calculated for all the remaining frames? In that case I would prefer the workaround Presented earlier (sleep in shorter periods while frames remained to be played).

This method would continue to wait even if the frames were dropped. This would be the case in the sigint handling pr for example.

**Comment by forslund** [comment]
Answering myself: I am wrong to assume that.

But how long is the sleep?

**Comment by forslund** [comment]
Tested it and it will sleep for a long time but otherwise it works nicely. I'll see if I can chop it up into abortable chunks and then I'll push it if there are no objections from you?

**Comment by zeehio** [comment]
The delay is defined as `the time that a frame that is written to the PCM stream shortly after this call will take to be actually audible` [alsa-doc](http://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga012e8b999070e72ab23514f25e7d6482), as there are no more samples written, it is safe to assume that all the samples will be written if we wait for that time.

Your approach with `snd_pcm_avail` may be better than mine, to me a `snd_pcm_drain` call should be able to wait (as we expected) and these are just workarounds that hopefully we will remove some day. Feel free to drop this and use yours if you think it makes more sense.

**Comment by forslund** [comment]
The thing is I trust you more than I trust myself with things concerning alsa =) I think this is slightly better to use than ```snd_pcm_avail``` as this gives an indication of the time that's needed for the frames to process. I've made the slight modifications needed to make this PR interruptable and will push it to development when I'm sure I've not made a mess of things.

You are right in pointing out that this is *hopefully* just a temporary workaround that should be removed eventually.

**Comment by zeehio** [comment]
@forslund Don't assume I know about ALSA... I don't think I know more than you. My solution was just "copy-pasted" from the [mailing list link](http://mailman.alsa-project.org/pipermail/alsa-devel/2012-November/057129.html) after reading  all I could find. I don't feel comfortable enough to defend my patch in any other way than referring to "it seems it works to other people, see the mailing list".

My hope is that if we make a mistake with that patch we are not the only ones, and if someone sees it they will hopefully report it and provide the right answer.

In any case, we should work on a good audio unit test. I will open an issue for that later if I can.

**Comment by forslund** [comment]
That's a very good idea!
Den 30 mar 2016 4:39 em skrev "Sergio Oller" <notifications@github.com>:

**Pull request merged**
