### PR TITLE
Updated alignment and details

### PR DESCRIPTION
**Pull request by anselm94**

### CODE REVIEW

**Comment by forslund** [comment]
I think it looks fine, many thanks for this. I'll assign @LongBoolean to provide additional comments and handle the merge when he's also happy with it.

**Comment by LongBoolean** [comment]
Looks pretty good. One change I would make is to make it more clear which platforms we have actually gotten mimic to run on, and have build instructions for doing so. For example, (please correct me if I am wrong) we have not gotten mimic to run on Android yet.(For that matter I don't even know if anyone has gotten it to compile on Windows) The flite codebase says that it worked on Android but if we haven't tried it with mimic, and don't have even some basic build instructions, I think we should make it clear to the reader of the situation. Ideally we don't want to confuse people into thinking that their platform is supported when it is only supported "in theory", only to have those people get angry when they dig deeper. 
In the same vein, iOS should not go under the "Supported Platforms" category as it is most definatly not currently supported. Perhaps both iOS and Android should go under a "Potential Future Platforms" category (or some better name) or "Untested Platforms", for Android anyway. 

Any way what do you guys think?

**Comment by anselm94** [comment]
I compiled mimic on a Debian Linux only. I too don't have any idea on any other platforms. I just restructured what was there previously in `README.md`. I added iOS as 'coming soon' since I found that being said in the official website.

May be we could add like as in the following?

**Platform Support**
------------------------
**Tested Platforms**
- Linux (ARM and Intel architectures)
- Mac OSX

**Untested Platforms**
- Android
- Windows

**Future Platforms**
- iOS

**Comment by zeehio** [comment]
@LongBoolean, Regarding iOS support there has been pull request #21 pending review. We need to test it or trust it.

I do believe that I have seen someone running it on Windows. Didn't @forslund provide some patches for mingw a few weeks ago?

**Comment by forslund** [comment]
I did some minor changes to get windows running. Together with @zeehio's portaudio addition everything works fine.

**Comment by LongBoolean** [comment]
@anselm94 yeah something like that would be better. 

@zeehio @forslund ok good, just wanted to make sure someone had gotten it to build on windows. Ideally we would have better build instructions for how to setup mimic to built on windows. (if there is anything different than what needs to happen on windows that doesn't on linux, visual studio related stuff and what not)

@zeehio I'm kind of torn when it comes to pull request #21, what it does is create a static lib that in theory can be used inside of an iOS app. So it is not as simple as, compile and run, if the user wanted to run mimic on iOS they would need to create an app of their own. Maybe that technically counts as supporting the platform, but it might also be confusing as none of the other supported platforms require that the user write the main that drives it.

**Comment by forslund** [comment]
@LongBoolean: currently I haven't had time to learn enough about visual studio to build it. From what I can see the current visual studio-project creates a dll. Building the commandline `mimic` requires bash or equivalent.

I currently build it under mingw when testing stuff on windows.

**Comment by forslund** [comment]
So to move this forward, the only change that is required is to do the changes that @anselm94 proposed with the exception that windows is tested to be able to run? The windows build procedure is standard when using *mingw*. If you wish I can add more details about the windows build later.

**Comment by LongBoolean** [comment]
@forslund yeah that would be fine.

**Comment by forslund** [comment]
@anselm94 could you take care of that?

**Pull request merged**
