### PR TITLE
Supress ls no such file error message

### PR DESCRIPTION
**Pull request by NoamDev**
* Description of what the PR does, such as fixes # {issue number}
When there are no dlls to copy, it seems like there's an error.
This change would supress the error message but wouldn't harm functionality.
* Description of how to validate or test this PR
The best way would be to check the method changed individually, in case there are dlls to copy and in case there are none.
* Whether you have signed a CLA (Contributor Licensing Agreement)
Yes

### CODE REVIEW

**Comment by NoamDev** [comment]
@forslund This one was for you, I didn't want the CI you're gonna build to fail because of that nonsense.
The checks failed, with no reason as far as I can tell.
Can someone force a recheck or is it pointless?
Edit: It doesn't seem to a coincidence but more like a problem with the task "shared".
Anyway, my changes didn't cause it.

**Comment by forslund** [comment]
I wonder if the correct way to do it is to remove the [move dll step](https://github.com/MycroftAI/mimic1/blob/development/run_testsuite.sh#L386) when doing static windows builds?

or do you see it when doing shared build as well?

**Comment by NoamDev** [comment]
I finished compiling and got exactly the same result with winbuild_shared.
Maybe it happens only in some cases/ubuntu versions and maybe it is related to the fact that I'm using wsl.
Anyway, removing the dll step will resolve nothing.

**Comment by NoamDev** [comment]
Even in the improbable scenario in which this happens only in wsl, it solves this specific problem and does not harm anyone else.
So why not;)

**Comment by forslund** [comment]
Agreed, Merging this and making a note to look at that again. Something may be wrong if nothing is ever copied...

**Pull request merged**
