### PR TITLE
Replace cmudict-0.4 dictionary with amepd.

### PR DESCRIPTION
**Pull request by forslund**
# What it is
Amepd (The american pronounciation dictionary) is a dictionary based on cmudict-0.7 with many additions. The source dictionary is available at http://github.com/rhdunn/amepd.

This would resolve the wrongly pronounced words listed in #15. @rhdunn the maintainer of the dictionary will add "Mycroft" to the dictionary in the next update and this should not be pulled before that time.

In the meantime it would be great if the dictionary was used and verified.

### CODE REVIEW

**Comment by rhdunn** [comment]
I have added Mycroft in the latest master commit to amepd, along with several new words and some pronunciation fixes.

**Comment by forslund** [comment]
Great! I'm currently out camping, but I'll update the PR with your updates when I return home (tomorrow evening, sunday  at the latest)

**Comment by ryanleesipes** [comment]
I'm also pulling this down to play with it. I'll try to find some time to provide feedback.

**Comment by rhdunn** [comment]
Not a problem with the dictionary, but as minic is removing `'` entries:

1.  `'d` sounds wrong in places -- it is not always `/IH0 D/`:

    a.  word ends with `/D/` or `/T/`, or is an adjective: use `/IH0 D/`;
    b.  the word ends with a voiced consonant or a vowel (e.g. `CALL'D`): use `/D/`;
    c.  otherwise the word ends with an unvoiced vowel (e.g. `BLESS'D` as a verb): use `/T/`.

    NOTE: This also needs to handle words like `ENCLOS'D`, where the `O` takes the `OW` rule for `oCe` words (an `o`, followed by a consonant, followed by an `e`).

2.  `'st` is not supported -- found e.g. in William Shakespeare's "The Phoenix and the Turtle" (Project Gutenberg 1525), such as `GIV'ST` (i.e. an -est ending, expanded to `GIVEST`): should be `/IH0 S T/`

**Comment by forslund** [comment]
Is 1 worse with the new dict than with the old cmudict-0.4? Can you give an example where mimic fails?

**Comment by forslund** [comment]
Just noticed the examples. Sorry about that :)

**Comment by rhdunn** [comment]
Not worse -- those words I gave as examples are where stripping out `'` entries does not always give the correct pronunciations in the listed cases with mimics handling of `'` entries. I'm using "The Phoenix and the Turtle" as a test case.

**Comment by forslund** [comment]
Ok. I'll have to dig into the code and see if we can improve this. At least for systems with larger memory...

**Comment by zeehio** [comment]
If I am not mistaken @rhdunn is taking care of the apostrophes in #39. 

If I understand this properly, @forslund you rebuilt the cmulex using the amepd dictionary and this pull request has the resulting models. To build this you used the lang/cmulex/make_cmulex script, replacing manually the lang/cmulex/festival/lib/dict/cmudict-0.4.scm file by the amepd dictionary, am I right?

**Comment by forslund** [comment]
@zeehio basically, yes. I changed the Makefile target for cmudict-0.4.out so that it's currently
```
cat amepd.scm cmudict_extensions.scm >all.scm
        ${ESTDIR}/../festival/bin/festival -b cmudict_compile.scm
        rm -f all.scm
```
and rebuilt the outfile. Also I created a no-setup target in the ```make-cmulex``` script

```
if [ $1 = "no-setup" ]
then
   $0 lts  || exit 1
   $0 lex  || exit 1
   $0 compresslex || exit 1
   $0 install || exit 1
   echo "make_cmulex finished successfully"
   exit 0
fi
```

So the files weren't overwritten.

**Comment by zeehio** [comment]
@forslund, keeping the first commit of this PR does not make much sense. Could you please squash them into one commit?

As I see it, feel free to merge :-)

**Comment by forslund** [comment]
After doing the manual squash I noticed the "squash and merge" github button. Anyway it's squashed and merged now.

**Comment by zeehio** [comment]
If I had known it existed I'd have merged myself

**Pull request merged**
