### PR TITLE
Remove PalmOS support.

### PR DESCRIPTION
**Pull request by zeehio**
Reasons:

- PalmOS is discontinued since 2009.
- `doc/mimic.texi` (from flite) stated that the code had not been  recently tested
- If nobody is able to test mimic on PalmOS we can't provide reliable support for it.
- git has the history, so we can bring PalmOS support back if required.

### CODE REVIEW

**Comment by ryanleesipes** [comment]
Haha! I second this!

**Comment by forslund** [comment]
A good idea! The PR looks good to me.

`<nitpicking>`The only question I have is why this changes the version? Is that really related to the palm OS change or is it a separate issue?`</nitpicking>`

**Comment by zeehio** [comment]
Right, it is a separate issue! We released 1.0.0 some weeks ago but we did not bump the version number in the configure script. We are not using that number, so I just updated it.

I forgot to split the commit, I just did it.

**Comment by forslund** [comment]
That's what I thought =)

Merging this.

**Pull request merged**
